kind: Service
apiVersion: v1
metadata:
  namespace: voting-app
  name: result
  labels:
    app: result
spec:
  ports:
    - port: 5002
      targetPort: 5002
  selector:
    app: result
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: result
  namespace: voting-app
  labels:
    app: result
spec:
  replicas: 1
  selector:
      matchLabels:
        app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: localhost:results-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        env:
          - name: FLASK_RUN_PORT
            value: "5002"
          - name: FLASK_RUN_HOST
            value: "0.0.0.0"
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            value: "password"
          - name: MYSQL_DB
            value: "votes"


