kind: Service
apiVersion: v1
metadata:
  namespace: voting-app
  name: result
  labels:
    app: result
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: result
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: result
  namespace: voting-app
  labels:
    app: result
spec:
  replicas: 1
  selector:
      matchLabels:
        app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: quay.io/massigollo/dsdb-workshop:results-v1
        ports:
        - containerPort: 5001
        env:
          ## value should be fetched from secret
          - name: FLASK_RUN_PORT
            value: "5001"
          - name: FLASK_RUN_HOST
            value: "0.0.0.0"
          - name: MONGO_USER
            value: "admin"
          - name: MONGO_PASSWORD
            value: "password"
          - name: MONGO_HOST
            value: "mongo"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_DB
            value: "votes"


