kind: Service
apiVersion: v1
metadata:
  namespace: voting-app
  name: vote
  labels:
    app: vote
spec:
  ports:
    - port: 5001
  selector:
    app: vote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting-app
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
      metadata:
        labels:
          app: vote
      spec:
        initContainers:
          - name: init-vote
            image: redis:alpine
            command: ['sh', '-c', 'until nc -z redis 6379; do echo "Waiting for Redis"; sleep 1; done;']
        containers:
        - name: vote
          image: voting-app:v1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5001
          env:
            - name: FLASK_RUN_PORT
              value: "5001"
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
