apiVersion: v1
kind: Service
metadata:
  namespace: voting-app
  name: worker
  labels:
    app: worker
spec:
  ports:
    - port: 5000
  selector:
    app: worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      ## initContainers are run before the main containers. The objective is to wait for the database to be ready before starting the worker
      initContainers:
        - name: init-mongo
          image: mongo
          command: ['sh', '-c', 'until mongo --host mongo:27017 --eval "quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)" &> /dev/null; do sleep 1; done;']
        - name: init-redis
          image: redis
          command: ['sh', '-c', 'until redis-cli -h redis ping &> /dev/null; do sleep 1; done;']
      containers:
        - name: worker
          image: quay.io/massigollo/dsdb-workshop:worker-go-v1
          imagePullPolicy: Always
          ports:
              - containerPort: 8080
          env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: MONGO_HOST
            value: "mongo"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_USER
            value: "admin"
          - name: MONGO_PASSWORD
            value: "password"
          - name: MONGO_DB
            value: "votes"

