apiVersion: v1
kind: Service
metadata:
  namespace: voting-app
  name: worker
  labels:
    app: worker
spec:
  ports:
    - port: 5000
  selector:
    app: worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
        - name: init-mysql
          image: busybox
          command: ['sh', '-c', 'until nslookup mysql.voting-app.svc.cluster.local >/dev/null 2>&1; do echo "Waiting for MySQL"; sleep 1; done;']
        - name: init-redis
          image: redis
          command: ['sh', '-c', 'until redis-cli -h redis ping &> /dev/null; do echo "Waiting for redis"; sleep 1; done;']
      containers:
        - name: worker
          image: localhost:worker-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASS
            value: "password"
          - name: MYSQL_DATABASE
            value: "votes"

