volumes:
  redis-data:
  mysql-data:

services:
  vote:
    image: voting-app:v1
    build:
      context: ./vote
      dockerfile: Dockerfile
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
        - 5001:5001

  results:
    image: results-app:v1
    build:
      context: ./results
      dockerfile: Dockerfile
    environment:
        - FLASK_RUN_HOST=0.0.0.0
        - FLASK_RUN_PORT=5002
        - MYSQL_HOST=mysql
        - MYSQL_PORT=3306
        - MYSQL_USER=root
        - MYSQL_PASSWORD=password
        - MYSQL_DB=votes
    ports:
      - 5002:5002

  worker:
    image: worker-app:v1
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - MYSQL_HOST=mysql
        - MYSQL_DATABASE=votes
        - MYSQL_PORT=3306
        - MYSQL_USER=root
        - MYSQL_PASS=password

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
        - redis-data:/data

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=votes
        - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080